-- Asset slots.
-- Paste asset ids here (a number, "123456" or "rbxassetid://123456").
-- Anything left empty falls back to procedural visuals or Roblox's built-in client sounds,
-- so the game is fully playable before a single asset is uploaded. TOOLBOX.md lists what to
-- look for in the Toolbox (Creator Store) for every slot.
--
-- Original sound effects for every key below are generated by tools/generate_sfx.py into
-- assets/sfx/<Key>.ogg. Upload them (Creator Hub > Development Items > Audio) and paste the ids.
--
-- Toolbox assets reach the game three ways, and the first one found wins:
--   1. Dragged straight from the Toolbox into ReplicatedStorage.ToolboxAssets.<Category>.<Slot>
--      in Studio (Rojo keeps anything you put in those folders).
--   2. Baked from the ids in Assets.Toolbox below by running this in the Studio command bar
--      (edit mode), then saving the place:
--        require(game.ServerScriptService.Server.Services.ToolboxService).install()
--   3. Loaded at runtime from the same ids by ToolboxService. InsertService can only load assets
--      the place's owner owns (so "Get" a free model to your inventory first) or Roblox made.
-- Every inserted asset is sanitized: scripts are deleted and parts are made non-colliding, so
-- a free model can never run code in the game.
--
--   ToolboxAssets.Models.Volleyball   -> any ball model (replaces the procedural ball)
--   ToolboxAssets.VFX.<Name>          -> a Part, Model or Attachment holding ParticleEmitters.
--        Impact names: SpikeImpact, PerfectImpact, ThunderImpact, AzureImpact, BlockImpact,
--        FloorImpact, ReceiveImpact, NetImpact, JumpBoom, GuardBreak. Each emitter fires
--        :Emit(n) where n = its "EmitCount" attribute (default 20).
--        AzureAura is held on the charging player instead (its emitters stay enabled).
--   ToolboxAssets.Sounds.<Key>        -> a Sound instance; overrides the matching key below.

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Assets = {}

Assets.Sounds = {
	Bump = "",
	ReceivePerfect = "",
	Set = "",
	Spike = "",
	SpikeHeavy = "",
	Thunder = "",
	AzureCharge = "",
	AzureRelease = "",
	Boom = "",
	Whoosh = "",
	Block = "",
	Stuff = "",
	FloorHit = "",
	NetHit = "",
	Toss = "",
	Serve = "",
	Slide = "",
	GuardBreak = "",
	Whistle = "",
	Timeout = "",
	UIClick = "",
	Point = "",
	CrowdLoop = "",
	CrowdCheer = "",
	CrowdGasp = "",
	Music = "",
}

-- Built-in client sounds (they ship with every Roblox install), pitched and distorted as stand-ins.
local LAND = "rbxasset://sounds/action_jump_land.mp3"
local PING = "rbxasset://sounds/electronicpingshort.wav"
local LUNGE = "rbxasset://sounds/swordlunge.wav"
local SLASH = "rbxasset://sounds/swordslash.wav"
Assets.Fallback = {
	Bump = { id = LAND, speed = 1.45, volume = 1.1 },
	ReceivePerfect = { id = LAND, speed = 1.7, volume = 1.3 },
	Set = { id = LAND, speed = 1.9, volume = 0.8 },
	Spike = { id = LAND, speed = 0.95, volume = 1.7, distort = 0.45 },
	SpikeHeavy = { id = LAND, speed = 0.62, volume = 2.2, distort = 0.6 },
	Thunder = { id = SLASH, speed = 0.45, volume = 1.4, distort = 0.7 },
	AzureCharge = { id = LUNGE, speed = 0.5, volume = 0.6 },
	AzureRelease = { id = LAND, speed = 0.5, volume = 2.2, distort = 0.65 },
	Boom = { id = LAND, speed = 0.55, volume = 1.2, distort = 0.35 },
	Whoosh = { id = LUNGE, speed = 1.15, volume = 0.7 },
	Block = { id = LAND, speed = 0.72, volume = 1.7, distort = 0.3 },
	Stuff = { id = LAND, speed = 0.58, volume = 2.0, distort = 0.5 },
	FloorHit = { id = LAND, speed = 0.82, volume = 1.3 },
	NetHit = { id = SLASH, speed = 0.55, volume = 0.5 },
	Toss = { id = LUNGE, speed = 1.6, volume = 0.35 },
	Serve = { id = LAND, speed = 1.1, volume = 1.3 },
	Slide = { id = "rbxasset://sounds/action_jump.mp3", speed = 0.8, volume = 0.9 },
	GuardBreak = { id = SLASH, speed = 0.4, volume = 1.2, distort = 0.5 },
	Whistle = { id = PING, speed = 1.7, volume = 0.45 },
	Timeout = { id = PING, speed = 1.3, volume = 0.5 },
	UIClick = { id = PING, speed = 2.2, volume = 0.3 },
	Point = { id = PING, speed = 1.2, volume = 0.55 },
}

-- Optional action animation ids. Roblox only plays animations owned by the place's owner (or by
-- Roblox), so a Toolbox animation has to be re-published from your account first (open its
-- KeyframeSequence in the Animation Editor and publish). When a slot is set, your own action
-- plays it (it replicates to everyone) and every client plays it on bots; the procedural pose
-- is skipped for that action.
Assets.Animations = {
	Bump = "",
	Set = "",
	Swing = "",
	Tip = "",
	Block = "",
	Slide = "",
	Charge = "",
	Toss = "",
	Stance = "",
	Knockback = "",
	Celebrate = "",
}

-- Locomotion for bots (they have no Animate script). These are Roblox's own default R15
-- animations, which every experience may play. Clear a slot to fall back to the procedural
-- run cycle.
Assets.BotAnimations = {
	Idle = "507766388",
	Run = "507767714",
	Jump = "507765000",
	Fall = "507767968",
}

-- Images: particle textures that ship with the client, and optional UI icons (Decal or Image
-- ids from the Toolbox). Empty icons fall back to text.
Assets.Images = {
	Spark = "rbxasset://textures/particles/sparkles_main.dds",
	Smoke = "rbxasset://textures/particles/smoke_main.dds",
	Fire = "rbxasset://textures/particles/fire_main.dds",
	AbilityThunder = "",
	AbilityAzure = "",
}

-- Custom ball mesh (see tools/generate_volleyball_asset.py). The generated OBJ has radius 1,
-- so a SpecialMesh scale equal to the ball radius makes it match the gameplay ball exactly.
Assets.Mesh = {
	BallMesh = "",
	BallTexture = "",
	BallMeshUnitRadius = 1,
}

-- Creator Store (Toolbox) asset ids that ToolboxService inserts into ToolboxAssets.<Category>.
-- Models and VFX only: sounds, animations and images take their ids in the tables above.
Assets.Toolbox = {
	Models = {
		Volleyball = "",
	},
	VFX = {
		SpikeImpact = "",
		PerfectImpact = "",
		ThunderImpact = "",
		AzureImpact = "",
		BlockImpact = "",
		FloorImpact = "",
		ReceiveImpact = "",
		NetImpact = "",
		JumpBoom = "",
		GuardBreak = "",
		AzureAura = "",
	},
}

function Assets.id(value)
	if value == nil or value == "" or value == 0 then
		return nil
	end
	if type(value) == "number" then
		return "rbxassetid://" .. tostring(value)
	end
	if string.find(value, "://", 1, true) then
		return value
	end
	return "rbxassetid://" .. value
end

-- The numeric id in any accepted form, or nil.
function Assets.number(value)
	if type(value) == "number" then
		return value > 0 and value or nil
	end
	if type(value) ~= "string" then
		return nil
	end
	local digits = string.match(value, "(%d+)%s*$")
	return digits and tonumber(digits) or nil
end

-- Look up ReplicatedStorage.ToolboxAssets.<dotted.path>
function Assets.toolbox(path)
	local node = ReplicatedStorage:FindFirstChild("ToolboxAssets")
	for piece in string.gmatch(path, "[^%.]+") do
		if not node then
			return nil
		end
		node = node:FindFirstChild(piece)
	end
	return node
end

-- Make an inserted asset inert: no scripts can run, and no part collides, casts shadows or
-- takes touches or raycasts. Returns the same instance.
function Assets.sanitize(inst)
	local doomed = {}
	local all = inst:GetDescendants()
	table.insert(all, inst)
	for _, d in ipairs(all) do
		if d:IsA("LuaSourceContainer") then
			table.insert(doomed, d)
		elseif d:IsA("BasePart") then
			d.Anchored = true
			d.CanCollide = false
			d.CanQuery = false
			d.CanTouch = false
			d.CastShadow = false
		end
	end
	for _, d in ipairs(doomed) do
		if d ~= inst then
			d:Destroy()
		end
	end
	return inst
end

return Assets
