-- Asset slots.
-- Paste asset ids here (a number, "123456" or "rbxassetid://123456").
-- Anything left empty falls back to procedural visuals or Roblox's built-in client sounds,
-- so the game is fully playable before a single asset is uploaded.
--
-- Original sound effects for every key below are generated by tools/generate_sfx.py into
-- assets/sfx/<Key>.ogg. Upload them (Creator Hub > Development Items > Audio) and paste the ids.
--
-- You can also drop models straight into ReplicatedStorage.ToolboxAssets:
--   ToolboxAssets.Models.Volleyball   -> any ball model (replaces the procedural ball)
--   ToolboxAssets.VFX.<Name>          -> a Part or Attachment holding ParticleEmitters.
--        Names used: SpikeImpact, PerfectImpact, ThunderImpact, AzureImpact, BlockImpact,
--        FloorImpact, ReceiveImpact. Each emitter fires :Emit(n) where n = its "EmitCount"
--        attribute (default 20).
--   ToolboxAssets.Sounds.<Key>        -> a Sound instance; overrides the matching key below.

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Assets = {}

Assets.Sounds = {
	Bump = "",
	ReceivePerfect = "",
	Set = "",
	Spike = "",
	SpikeHeavy = "",
	Thunder = "",
	AzureCharge = "",
	AzureRelease = "",
	Boom = "",
	Whoosh = "",
	Block = "",
	Stuff = "",
	FloorHit = "",
	NetHit = "",
	Toss = "",
	Serve = "",
	Slide = "",
	GuardBreak = "",
	Whistle = "",
	Timeout = "",
	UIClick = "",
	Point = "",
	CrowdLoop = "",
	CrowdCheer = "",
	CrowdGasp = "",
	Music = "",
}

-- Built-in client sounds (they ship with every Roblox install), pitched and distorted as stand-ins.
local LAND = "rbxasset://sounds/action_jump_land.mp3"
local PING = "rbxasset://sounds/electronicpingshort.wav"
local LUNGE = "rbxasset://sounds/swordlunge.wav"
local SLASH = "rbxasset://sounds/swordslash.wav"
Assets.Fallback = {
	Bump = { id = LAND, speed = 1.45, volume = 1.1 },
	ReceivePerfect = { id = LAND, speed = 1.7, volume = 1.3 },
	Set = { id = LAND, speed = 1.9, volume = 0.8 },
	Spike = { id = LAND, speed = 0.95, volume = 1.7, distort = 0.45 },
	SpikeHeavy = { id = LAND, speed = 0.62, volume = 2.2, distort = 0.6 },
	Thunder = { id = SLASH, speed = 0.45, volume = 1.4, distort = 0.7 },
	AzureCharge = { id = LUNGE, speed = 0.5, volume = 0.6 },
	AzureRelease = { id = LAND, speed = 0.5, volume = 2.2, distort = 0.65 },
	Boom = { id = LAND, speed = 0.55, volume = 1.2, distort = 0.35 },
	Whoosh = { id = LUNGE, speed = 1.15, volume = 0.7 },
	Block = { id = LAND, speed = 0.72, volume = 1.7, distort = 0.3 },
	Stuff = { id = LAND, speed = 0.58, volume = 2.0, distort = 0.5 },
	FloorHit = { id = LAND, speed = 0.82, volume = 1.3 },
	NetHit = { id = SLASH, speed = 0.55, volume = 0.5 },
	Toss = { id = LUNGE, speed = 1.6, volume = 0.35 },
	Serve = { id = LAND, speed = 1.1, volume = 1.3 },
	Slide = { id = "rbxasset://sounds/action_jump.mp3", speed = 0.8, volume = 0.9 },
	GuardBreak = { id = SLASH, speed = 0.4, volume = 1.2, distort = 0.5 },
	Whistle = { id = PING, speed = 1.7, volume = 0.45 },
	Timeout = { id = PING, speed = 1.3, volume = 0.5 },
	UIClick = { id = PING, speed = 2.2, volume = 0.3 },
	Point = { id = PING, speed = 1.2, volume = 0.55 },
}

-- Optional animation ids. When set, the local player's action plays the uploaded animation
-- (it replicates to everyone) instead of the procedural pose. Bots always use procedural poses.
Assets.Animations = {
	Bump = "",
	Set = "",
	Swing = "",
	Tip = "",
	Block = "",
	Slide = "",
	Charge = "",
	Toss = "",
	Celebrate = "",
}

-- Particle textures that ship with the client.
Assets.Images = {
	Spark = "rbxasset://textures/particles/sparkles_main.dds",
	Smoke = "rbxasset://textures/particles/smoke_main.dds",
	Fire = "rbxasset://textures/particles/fire_main.dds",
}

-- Custom ball mesh (see tools/generate_volleyball_asset.py). The generated OBJ has radius 1,
-- so a SpecialMesh scale equal to the ball radius makes it match the gameplay ball exactly.
Assets.Mesh = {
	BallMesh = "",
	BallTexture = "",
	BallMeshUnitRadius = 1,
}

function Assets.id(value)
	if value == nil or value == "" or value == 0 then
		return nil
	end
	if type(value) == "number" then
		return "rbxassetid://" .. tostring(value)
	end
	if string.find(value, "://", 1, true) then
		return value
	end
	return "rbxassetid://" .. value
end

-- Look up ReplicatedStorage.ToolboxAssets.<dotted.path>
function Assets.toolbox(path)
	local node = ReplicatedStorage:FindFirstChild("ToolboxAssets")
	for piece in string.gmatch(path, "[^%.]+") do
		if not node then
			return nil
		end
		node = node:FindFirstChild(piece)
	end
	return node
end

return Assets
