-- GENERATED by tools/generate_roster.py: edit the templates there and re-run.
-- The named preset characters you roll for with V Points. Each has a role (WS wing
-- spiker, MB middle blocker, SE setter), a tier, a height (cm), four stats and maybe an
-- ability (Config.Abilities). Starters are owned by everyone.

local Roster = {
	{ Id = "seojin", Name = "Seojin", Role = "WS", Tier = "S+", Height = 184, Attack = 210, Defense = 128, Speed = 140, Jump = 175, Ability = "Azure" },
	{ Id = "yejun", Name = "YeJun", Role = "WS", Tier = "S+", Height = 189, Attack = 210, Defense = 124, Speed = 146, Jump = 190, Ability = "Thunder" },
	{ Id = "hayun", Name = "Hayun", Role = "WS", Tier = "S", Height = 187, Attack = 198, Defense = 126, Speed = 142, Jump = 181, Ability = "Adrenaline" },
	{ Id = "shoyo", Name = "Shoyo", Role = "WS", Tier = "S", Height = 181, Attack = 190, Defense = 118, Speed = 150, Jump = 186, Ability = "Adrenaline" },
	{ Id = "gaeul", Name = "Gaeul", Role = "MB", Tier = "S", Height = 204, Attack = 170, Defense = 150, Speed = 116, Jump = 180, Ability = "IronWall" },
	{ Id = "tetsuo", Name = "Tetsuo", Role = "MB", Tier = "S", Height = 201, Attack = 166, Defense = 158, Speed = 112, Jump = 178, Ability = "IronWall" },
	{ Id = "akira", Name = "Akira", Role = "SE", Tier = "S", Height = 180, Attack = 134, Defense = 178, Speed = 168, Jump = 136, Ability = "ChainReaction" },
	{ Id = "seoyeon", Name = "Seoyeon", Role = "SE", Tier = "S", Height = 176, Attack = 128, Defense = 172, Speed = 178, Jump = 140, Ability = "ChainReaction" },
	{ Id = "aoi", Name = "Aoi", Role = "WS", Tier = "A+", Height = 182, Attack = 190, Defense = 119, Speed = 131, Jump = 175, Ability = nil },
	{ Id = "kenji", Name = "Kenji", Role = "MB", Tier = "A+", Height = 201, Attack = 155, Defense = 133, Speed = 114, Jump = 160, Ability = nil },
	{ Id = "rin", Name = "Rin", Role = "SE", Tier = "A+", Height = 179, Attack = 125, Defense = 157, Speed = 167, Jump = 126, Ability = nil },
	{ Id = "sora", Name = "Sora", Role = "WS", Tier = "A-", Height = 186, Attack = 178, Defense = 115, Speed = 124, Jump = 163, Ability = nil },
	{ Id = "itsuki", Name = "Itsuki", Role = "MB", Tier = "A-", Height = 200, Attack = 148, Defense = 133, Speed = 97, Jump = 151, Ability = nil },
	{ Id = "mio", Name = "Mio", Role = "SE", Tier = "A-", Height = 177, Attack = 117, Defense = 145, Speed = 149, Jump = 124, Ability = nil },
	{ Id = "jiwon", Name = "Jiwon", Role = "WS", Tier = "B+", Height = 192, Attack = 168, Defense = 103, Speed = 114, Jump = 154, Ability = nil },
	{ Id = "yuna", Name = "Yuna", Role = "MB", Tier = "B+", Height = 202, Attack = 134, Defense = 119, Speed = 99, Jump = 151, Ability = nil },
	{ Id = "minjae", Name = "Minjae", Role = "SE", Tier = "B+", Height = 181, Attack = 109, Defense = 142, Speed = 141, Jump = 121, Ability = nil },
	{ Id = "nagi", Name = "Nagi", Role = "WS", Tier = "B-", Height = 188, Attack = 149, Defense = 107, Speed = 108, Jump = 145, Ability = nil },
	{ Id = "yuto", Name = "Yuto", Role = "MB", Tier = "B-", Height = 199, Attack = 126, Defense = 115, Speed = 99, Jump = 137, Ability = nil },
	{ Id = "minseo", Name = "Minseo", Role = "SE", Tier = "B-", Height = 172, Attack = 98, Defense = 138, Speed = 140, Jump = 107, Ability = nil },
	{ Id = "jiho", Name = "Jiho", Role = "WS", Tier = "C+", Height = 191, Attack = 145, Defense = 96, Speed = 110, Jump = 137, Ability = nil },
	{ Id = "hyunwoo", Name = "Hyunwoo", Role = "MB", Tier = "C+", Height = 204, Attack = 119, Defense = 110, Speed = 88, Jump = 128, Ability = nil },
	{ Id = "hikari", Name = "Hikari", Role = "SE", Tier = "C+", Height = 182, Attack = 95, Defense = 130, Speed = 128, Jump = 108, Ability = nil },
	{ Id = "eunwoo", Name = "Eunwoo", Role = "WS", Tier = "C-", Height = 188, Attack = 129, Defense = 87, Speed = 104, Jump = 121, Ability = nil },
	{ Id = "ren", Name = "Ren", Role = "MB", Tier = "C-", Height = 201, Attack = 109, Defense = 102, Speed = 88, Jump = 117, Ability = nil },
	{ Id = "dohyun", Name = "Dohyun", Role = "SE", Tier = "C-", Height = 178, Attack = 97, Defense = 122, Speed = 118, Jump = 93, Ability = nil },
	{ Id = "kaede", Name = "Kaede", Role = "WS", Tier = "D+", Height = 187, Attack = 125, Defense = 91, Speed = 102, Jump = 117, Ability = nil },
	{ Id = "kaito", Name = "Kaito", Role = "MB", Tier = "D+", Height = 206, Attack = 106, Defense = 104, Speed = 80, Jump = 111, Ability = nil },
	{ Id = "asahi", Name = "Asahi", Role = "SE", Tier = "D+", Height = 174, Attack = 86, Defense = 114, Speed = 108, Jump = 91, Ability = nil },
	{ Id = "riku", Name = "Riku", Role = "WS", Tier = "D", Height = 192, Attack = 123, Defense = 84, Speed = 98, Jump = 117, Ability = nil },
	{ Id = "daichi", Name = "Daichi", Role = "MB", Tier = "D", Height = 199, Attack = 107, Defense = 94, Speed = 81, Jump = 115, Ability = nil },
	{ Id = "hana", Name = "Hana", Role = "SE", Tier = "D", Height = 170, Attack = 82, Defense = 103, Speed = 106, Jump = 87, Ability = nil },
}

Roster.Starters = { "riku", "daichi", "hana" }

local byId = {}
for _, c in ipairs(Roster) do
	byId[c.Id] = c
end

function Roster.get(id)
	return byId[id or ""]
end

return Roster
